# =============================================================================
# M365 Migration - Project Configuration File
# Generated by New-ProjectConfig.ps1 on {{GeneratedDate}}
# =============================================================================
# DO NOT run this file directly. Dot-source it before calling migration functions
# or pass it to Start-Migration.ps1 via the -ConfigPath parameter.
#
# Usage:
#   . .\{{ProjectKey}}-Config.ps1
#   OR
#   Start-Migration -ConfigPath ".\{{ProjectKey}}-Config.ps1" -Phase export
# =============================================================================

# --- Project Identity ---
$ProjectKey   = "{{ProjectKey}}"    # Unique key for this migration project (used in file names)

# --- Domains ---
$Domain       = "{{Domain}}"        # Source tenant primary domain (e.g. acme.com)
$DestDomain   = "{{DestinationDomain}}" # Destination tenant domain (e.g. amorim.rocks)

# --- Optional alias prefix ---
# Leave empty for no prefix. When set, destination aliases become: <Prefix>-<localPart>@<DestDomain>
$Prefix       = "{{Prefix}}"

# --- File System Paths ---
$CSVFolder    = "{{CSVFolder}}"     # Base directory for all CSV exports and imports
$CSVSource    = Join-Path $CSVFolder $ProjectKey   # Project-specific CSV subfolder
$LogFolder    = Join-Path $CSVFolder "$ProjectKey\Logs"  # Log file output folder

# --- Ensure directories exist ---
foreach ($dir in @($CSVSource, $LogFolder)) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
}

Write-Host "[Config] Project '$ProjectKey' loaded. CSVSource: $CSVSource" -ForegroundColor DarkGray
